export const TEAMS = [
    // ---------------- EAST ----------------
    { teamId: 1, name: "UConn", seed: 1, rating: 94, region: "East", playStyle: "slow" },
    { teamId: 2, name: "Stetson", seed: 16, rating: 66, region: "East", playStyle: "fast" },
    { teamId: 3, name: "FAU", seed: 8, rating: 82, region: "East", playStyle: "fast" },
    { teamId: 4, name: "Northwestern", seed: 9, rating: 81, region: "East", playStyle: "balanced" },
    { teamId: 5, name: "Auburn", seed: 5, rating: 87, region: "East", playStyle: "fast" },
    { teamId: 6, name: "Yale", seed: 12, rating: 74, region: "East", playStyle: "slow" },
    { teamId: 7, name: "BYU", seed: 4, rating: 86, region: "East", playStyle: "fast" },
    { teamId: 8, name: "Duquesne", seed: 13, rating: 73, region: "East", playStyle: "slow" },
    { teamId: 9, name: "Illinois", seed: 3, rating: 89, region: "East", playStyle: "fast" },
    { teamId: 10, name: "Morehead State", seed: 14, rating: 70, region: "East", playStyle: "slow" },
    { teamId: 11, name: "Washington State", seed: 6, rating: 84, region: "East", playStyle: "slow" },
    { teamId: 12, name: "Drake", seed: 11, rating: 78, region: "East", playStyle: "balanced" },
    { teamId: 13, name: "Iowa State", seed: 2, rating: 91, region: "East", playStyle: "slow" },
    { teamId: 14, name: "South Dakota State", seed: 15, rating: 68, region: "East", playStyle: "fast" },
    { teamId: 15, name: "San Diego State", seed: 7, rating: 83, region: "East", playStyle: "slow" },
    { teamId: 16, name: "UAB", seed: 10, rating: 79, region: "East", playStyle: "fast" },
  
    // ---------------- WEST ----------------
    { teamId: 17, name: "North Carolina", seed: 1, rating: 93, region: "West", playStyle: "fast" },
    { teamId: 18, name: "Wagner", seed: 16, rating: 65, region: "West", playStyle: "slow" },
    { teamId: 19, name: "Mississippi State", seed: 8, rating: 82, region: "West", playStyle: "slow" },
    { teamId: 20, name: "Michigan State", seed: 9, rating: 81, region: "West", playStyle: "balanced" },
    { teamId: 21, name: "Saint Mary's", seed: 5, rating: 86, region: "West", playStyle: "slow" },
    { teamId: 22, name: "Grand Canyon", seed: 12, rating: 76, region: "West", playStyle: "fast" },
    { teamId: 23, name: "Alabama", seed: 4, rating: 87, region: "West", playStyle: "fast" },
    { teamId: 24, name: "College of Charleston", seed: 13, rating: 72, region: "West", playStyle: "fast" },
    { teamId: 25, name: "Baylor", seed: 3, rating: 88, region: "West", playStyle: "fast" },
    { teamId: 26, name: "Colgate", seed: 14, rating: 70, region: "West", playStyle: "slow" },
    { teamId: 27, name: "Clemson", seed: 6, rating: 84, region: "West", playStyle: "balanced" },
    { teamId: 28, name: "New Mexico", seed: 11, rating: 80, region: "West", playStyle: "fast" },
    { teamId: 29, name: "Arizona", seed: 2, rating: 92, region: "West", playStyle: "fast" },
    { teamId: 30, name: "Long Beach State", seed: 15, rating: 67, region: "West", playStyle: "fast" },
    { teamId: 31, name: "Dayton", seed: 7, rating: 83, region: "West", playStyle: "slow" },
    { teamId: 32, name: "Nevada", seed: 10, rating: 79, region: "West", playStyle: "balanced" },
  
    // ---------------- MIDWEST ----------------
    { teamId: 33, name: "Purdue", seed: 1, rating: 95, region: "Midwest", playStyle: "slow" },
    { teamId: 34, name: "Grambling State", seed: 16, rating: 65, region: "Midwest", playStyle: "fast" },
    { teamId: 35, name: "Utah State", seed: 8, rating: 82, region: "Midwest", playStyle: "fast" },
    { teamId: 36, name: "TCU", seed: 9, rating: 81, region: "Midwest", playStyle: "fast" },
    { teamId: 37, name: "Gonzaga", seed: 5, rating: 87, region: "Midwest", playStyle: "fast" },
    { teamId: 38, name: "McNeese State", seed: 12, rating: 75, region: "Midwest", playStyle: "balanced" },
    { teamId: 39, name: "Kansas", seed: 4, rating: 88, region: "Midwest", playStyle: "balanced" },
    { teamId: 40, name: "Samford", seed: 13, rating: 73, region: "Midwest", playStyle: "fast" },
    { teamId: 41, name: "Creighton", seed: 3, rating: 89, region: "Midwest", playStyle: "fast" },
    { teamId: 42, name: "Akron", seed: 14, rating: 70, region: "Midwest", playStyle: "slow" },
    { teamId: 43, name: "South Carolina", seed: 6, rating: 84, region: "Midwest", playStyle: "slow" },
    { teamId: 44, name: "Oregon", seed: 11, rating: 80, region: "Midwest", playStyle: "fast" },
    { teamId: 45, name: "Tennessee", seed: 2, rating: 92, region: "Midwest", playStyle: "fast" },
    { teamId: 46, name: "Saint Peter's", seed: 15, rating: 67, region: "Midwest", playStyle: "slow" },
    { teamId: 47, name: "Texas", seed: 7, rating: 83, region: "Midwest", playStyle: "fast" },
    { teamId: 48, name: "Colorado State", seed: 10, rating: 79, region: "Midwest", playStyle: "balanced" },
  
    // ---------------- SOUTH ----------------
    { teamId: 49, name: "Houston", seed: 1, rating: 96, region: "South", playStyle: "slow" },
    { teamId: 50, name: "Longwood", seed: 16, rating: 65, region: "South", playStyle: "fast" },
    { teamId: 51, name: "Nebraska", seed: 8, rating: 82, region: "South", playStyle: "balanced" },
    { teamId: 52, name: "Texas A&M", seed: 9, rating: 81, region: "South", playStyle: "fast" },
    { teamId: 53, name: "Wisconsin", seed: 5, rating: 86, region: "South", playStyle: "slow" },
    { teamId: 54, name: "James Madison", seed: 12, rating: 78, region: "South", playStyle: "fast" },
    { teamId: 55, name: "Duke", seed: 4, rating: 88, region: "South", playStyle: "balanced" },
    { teamId: 56, name: "Vermont", seed: 13, rating: 72, region: "South", playStyle: "slow" },
    { teamId: 57, name: "Texas Tech", seed: 3, rating: 87, region: "South", playStyle: "fast" },
    { teamId: 58, name: "Western Kentucky", seed: 14, rating: 70, region: "South", playStyle: "fast" },
    { teamId: 59, name: "Kentucky", seed: 6, rating: 85, region: "South", playStyle: "fast" },
    { teamId: 60, name: "Oakland", seed: 11, rating: 79, region: "South", playStyle: "fast" },
    { teamId: 61, name: "Marquette", seed: 2, rating: 91, region: "South", playStyle: "fast" },
    { teamId: 62, name: "Western Carolina", seed: 15, rating: 67, region: "South", playStyle: "slow" },
    { teamId: 63, name: "Florida", seed: 7, rating: 84, region: "South", playStyle: "fast" },
    { teamId: 64, name: "Boise State", seed: 10, rating: 79, region: "South", playStyle: "balanced" },
  ];
  